apiVersion: admissionregistration.x-k8s.io/v1alpha1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: cluster-policy-deny-host-mount-binding
spec:
  policyName: cluster-policy-deny-host-mount
  validationActions:
  - Deny
  - Audit