apiVersion: admissionregistration.x-k8s.io/v1alpha1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: cluster-policy-deny-hostMount-binding
spec:
  policyName: cluster-policy-deny-hostMount
  validationActions:
  - Deny
  - Audit