apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kubeenforcer.clusterRoleName" . }}
rules:
- apiGroups:
  - admissionregistration.x-k8s.io
  resources:
  - validatingadmissionpolicies
  - validatingadmissionpolicybindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups: 
  - admissionregistration.x-k8s.io
  resources:
  - validatingadmissionpolicies/status
  verbs:
  - update
