{{- if .Values.admissionWebhook.generateSelfSignedCertificates -}}
{{- $ca := genCA (printf "*.%s.svc" (include "kubeenforcer.namespace" .)) 1024 -}}
{{- $svcName := (printf "%s.%s.svc" (include "kubeenforcer.admission-controller.serviceName" .) (include "kubeenforcer.namespace" .)) -}}
{{- $cert := genSignedCert $svcName nil (list $svcName) 1024 $ca -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeenforcer.fullname" . }}-ca
  namespace: {{ template "kubeenforcer.namespace" . }}
  labels:
    {{- include "kubeenforcer.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.key: {{ $ca.Key | b64enc }}
  tls.crt: {{ $ca.Cert | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubeenforcer.fullname" . }}-tls
  namespace: {{ template "kubeenforcer.namespace" . }}
  labels:
    {{- include "kubeenforcer.labels" . | nindent 4 }}
  annotations:
    self-signed-cert: "true"
type: kubernetes.io/tls
data:
  tls.key: {{ $cert.Key | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "kubeenforcer.name" . }}
  namespace: {{ include "kubeenforcer.namespace" . }}
webhooks:
  - name: webhook.{{ include "kubeenforcer.name" . }}.io
    failurePolicy: Ignore
    rules:
      - apiGroups: ["*"]
        apiVersions: ["*"]
        operations: ["*"]
        resources: ["*", "pods/*"]
        scope: "*"
    clientConfig:
      service:
        namespace: {{ include "kubeenforcer.namespace" . }}
        name: {{ include "kubeenforcer.admission-controller.serviceName" . }}
        path: /validate
        port: 443
      caBundle: {{ $ca.Cert | b64enc }}
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 2
    namespaceSelector:
      matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values:
        - "kube-system"
        - "kube-node-lease"
        - "kube-public"
        - {{ include "kubeenforcer.namespace" . }}
{{- end -}}