apiVersion: admissionregistration.x-k8s.io/v1alpha1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: cluster-policy-deny-privileged-flag-binding
spec:
  policyName: cluster-policy-deny-priviliged-flag
  validationActions:
  - Deny
  - Audit