apiVersion: admissionregistration.x-k8s.io/v1alpha1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: cluster-policy-deny-attach-binding
spec:
  policyName: cluster-policy-deny-attach
  validationActions:
  - Audit