apiVersion: admissionregistration.x-k8s.io/v1alpha1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: cluster-policy-deny-insecure-capabilities-binding
spec:
  policyName: cluster-policy-deny-insecure-capabilities
  paramRef:
    name: basic-policy-configuration
  validationActions:
  - Audit