apiVersion: admissionregistration.x-k8s.io/v1alpha1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: cluster-policy-insecure-capabilities-binding
spec:
  policyName: cluster-policy-insecure-capabilities
  paramRef:
    name: basic-control-configuration
  validationActions:
  - Audit