apiVersion: admissionregistration.x-k8s.io/v1alpha1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: cluster-policy-deny-exec-binding
spec:
  policyName: cluster-policy-deny-exec
  validationActions:
  - Deny
  - Audit